# Generated by Django 3.0.4 on 2020-04-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200411_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date of edit'),
        ),
        migrations.AddField(
            model_name='page',
            name='published',
            field=models.SlugField(default=True, max_length=100, unique=True, verbose_name='url'),
        ),
        migrations.AddField(
            model_name='page',
            name='published_date',
            field=models.CharField(default='page/index.html', max_length=500),
        ),
        migrations.AddField(
            model_name='page',
            name='registration_required',
            field=models.BooleanField(default=False, help_text='If you check this in checkbox, only authenticated users can see page'),
        ),
        migrations.AddField(
            model_name='page',
            name='sub_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(default='blog/post_detail.html', max_length=500),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('slug',)},
        ),
        migrations.RemoveField(
            model_name='page',
            name='active',
        ),
    ]
