# Generated by Django 3.0.4 on 2020-04-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200426_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='published',
            field=models.SlugField(default=True, verbose_name='Publish?'),
        ),
        migrations.AlterField(
            model_name='page',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='registration_required',
            field=models.BooleanField(default=False, help_text='If you check this checkbox, only authenticated users can see page'),
        ),
        migrations.AlterField(
            model_name='page',
            name='sub_title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Sub title'),
        ),
    ]
