# Generated by Django 3.0.4 on 2020-04-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200426_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Publish?'),
        ),
    ]
