# Generated by Django 3.0.4 on 2020-03-12 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='url')),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('template', models.CharField(default='blog/post_list.html', max_length=500)),
                ('published', models.BooleanField(default=True, verbose_name='Publicate?')),
                ('paginated', models.PositiveIntegerField(default=5, verbose_name='amount of articles on single page')),
                ('sort', models.PositiveIntegerField(default=0)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tag')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('published', models.BooleanField(default=True, verbose_name='Show tag?')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('mini_text', models.TextField(max_length=100, verbose_name='Mini Text')),
                ('text', models.TextField(max_length=16000, verbose_name='Text')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('edit_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Edit date')),
                ('published_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Publication date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='post/', verbose_name='Main photo')),
                ('template', models.CharField(default='blog/post_detail.html', max_length=500)),
                ('published', models.BooleanField(default=True, verbose_name='Publicate?')),
                ('viewed', models.PositiveIntegerField(default=0)),
                ('status', models.BooleanField(default=False, verbose_name='For Registered')),
                ('sort', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='Category')),
                ('tags', models.ManyToManyField(blank=True, to='blog.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=244, verbose_name='Text')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('moderation', models.BooleanField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post', verbose_name='Article')),
            ],
            options={
                'verbose_name_plural': 'commentaries',
            },
        ),
    ]
