# Generated by Django 3.0.4 on 2020-03-12 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_commentary_post_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentary',
            options={'verbose_name_plural': 'commentaries'},
        ),
    ]
