# Generated by Django 3.0.4 on 2020-04-11 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200410_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['sort', '-published_date']},
        ),
    ]
