# Generated by Django 3.0.4 on 2020-04-12 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200412_0219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-sort', '-published_date']},
        ),
    ]
