# Generated by Django 3.0.4 on 2020-04-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_main',
            name='level',
        ),
        migrations.RemoveField(
            model_name='menu_main',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='menu_main',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='menu_main',
            name='tree_id',
        ),
    ]
